apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.postgresql.enabled }}
  {{- $postgrestmp := printf "%s-%s" .Release.Name "postgresql"}}
  #postgres_host: "{{ $postgrestmp |b64enc }}"
  {{- if .Values.postgresql.enabled }}
  {{- $dbHost := printf "%s-%s" .Release.Name "postgresql" }}
  {{- if .Values.postgresql.fullnameOverride }}
    {{- $dbHost = .Values.postgresql.fullnameOverride }}
  {{- end }}
  postgres_host: "{{ $dbHost | b64enc }}"
{{- end }}
  postgres_username: "{{ .Values.postgresql.postgresqlUsername | b64enc }}"
  postgres_password: "{{ .Values.postgresql.postgresqlPassword | toString | b64enc }}"
  postgres_database: "{{ .Values.postgresql.postgresqlDatabase | b64enc }}"
{{ end }}
{{- if .Values.mariadb.enabled }}
  {{- $mysqltmp := printf "%s-%s" .Release.Name "mariadb"}}
  mysql_host: "{{ $mysqltmp |  b64enc }}"
  mysql_username: "{{ .Values.powerdns.mysql.username | b64enc }}"
  mysql_password: "{{ .Values.powerdns.mysql.password | toString | b64enc }}"
  mysql_database: "{{ .Values.powerdns.mysql.database | b64enc }}"
{{ end }}
